### ISSUE TITLE
I tried stroll, but clang does file moves, stroll says 'nope'

### ISSUE THREAD

**Issue by drudru** [snowleopard/stroll#6]
Hi, I tried stroll.
However, it stated. "stroll: Moving files not supported"

Clang writes to a .o.tmp and then moves it to its final .o file.
This is actually a good practice.

Can stroll support this?

**Comment by snowleopard** [comment]
I think it's actually not hard: I'm guessing the `Move x y` event can be recorded as reading `x` and writing `y`. 

I didn't have time to think about this more deeply. If you'd like to try changing Stroll to support file moves, I'm happy to discuss further/review a PR.

**Comment by drudru** [comment]
Hi, I don't know Haskell. Thanks though.
